/*user consist of 3 types, student, tutor and admin
the user madel store the information in registration
all are common attributes for either student or tutor
*/

const mongoose = require("mongoose")


const userSchema = mongoose.Schema({
  userid: Number,  //generated by counting the number of tuples
  realname:{ type: String, required: true},
  username: { type: String, required: true, unique: true },
  phonenumber: { type: Number, required: true, unique: true },
  email: { type: String, required: true, unique: true },
  role: String, //indicate the user is a student or tutor
  isVerified: Boolean,
  password: { type: String, required: true} //should be salted

  
})

module.exports = mongoose.model("User",userSchema)


